/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlleur.ControllerLocal;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Observer;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.Joueur;
import model.NumeroJoueur;
import model.Parametre;
import model.Partie;
import model.Piece;

/**
 *
 * @author timotheetroncy
 */
public class JPanelMenu extends javax.swing.JPanel {

    /**
     * Creates new form JPanelMenu
     */
    public JPanelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonParametrer = new javax.swing.JButton();
        jButtonCommencer = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setName("menu"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jButtonParametrer.setText("Paramétrer Partie");
        jButtonParametrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParametrerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(87, 106, 0, 107);
        add(jButtonParametrer, gridBagConstraints);

        jButtonCommencer.setText("Commencer nouvelle partie");
        jButtonCommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommencerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -33;
        gridBagConstraints.ipady = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 106, 96, 107);
        add(jButtonCommencer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonParametrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParametrerActionPerformed
        CardLayout cl = (CardLayout) this.getParent().getLayout();
        cl.show(this.getParent(), "parametres");
    }//GEN-LAST:event_jButtonParametrerActionPerformed

    private void jButtonCommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommencerActionPerformed
        Parametre p = new Parametre(true, true, true, true, true);
        Joueur j1 = new Joueur("Joueur 1", false, NumeroJoueur.J1);
        Joueur j2 = new Joueur("Joueur 2", false, NumeroJoueur.J2);
        Piece.instanciationNb = 0;
        Partie partie = new Partie(p, j1, j2);
        ControllerLocal controllerLocal = new ControllerLocal(partie);
        JPanel panel = new JPanelQuarto(controllerLocal);
        controllerLocal.addObserver((Observer) panel);
        panel.setName("jeu");//important

        CardLayout cl = (CardLayout) this.getParent().getLayout();

        //on remove le component jeu
        Component[] components = this.getParent().getComponents();
        for (Component c : components) {
            if (c.getName().equals("jeu")) {
                cl.removeLayoutComponent(c);
                this.getParent().remove(c);
            }
        }
        this.getParent().add("jeu", panel);

        cl.show(this.getParent(), "jeu");

        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.pack();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation(dim.width / 2 - frame.getSize().width / 2, dim.height / 2 - frame.getSize().height / 2);


    }//GEN-LAST:event_jButtonCommencerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCommencer;
    private javax.swing.JButton jButtonParametrer;
    // End of variables declaration//GEN-END:variables
}
