/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.local;

import static Network.RMI.Implementation.Constantes.URL_CONNEXION;
import Network.RMI.Interface.ILogin;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.security.auth.login.LoginException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static launcher.local.PartieBuilder.repackPartieQuarto;
import view.remote.ModeReseau2;

/**
 *
 * @author Anis
 */
public class JPanelMenuPrincipal extends javax.swing.JPanel {

    private final Image backgroundImage;
    private JPanel generalPanel;

    /**
     * Creates new form JPanelMenuPrincipal
     */
    public JPanelMenuPrincipal() {
        initComponents();
        this.backgroundImage = GUIImageTool.getImage("/images/wood_texture.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLocal = new javax.swing.JButton();
        jButtonRemote = new javax.swing.JButton();

        jButtonLocal.setText("Joueur en local");
        jButtonLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalActionPerformed(evt);
            }
        });

        jButtonRemote.setText("Joueur en réseau");
        jButtonRemote.setPreferredSize(new java.awt.Dimension(150, 29));
        jButtonRemote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jButtonRemote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jButtonLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRemote, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoteActionPerformed

        
        
        try {
            ILogin service = (ILogin) Naming.lookup(URL_CONNEXION);
            
            try {
                service.connexion("", "");
            } catch (LoginException ex) {
            }

            JFrame frame = (JFrame) SwingUtilities.getRoot(this);

            frame.setContentPane(ModeReseau2.getInstance(service));

            repackPartieQuarto((JPanel) frame.getContentPane());

        } catch (NotBoundException | MalformedURLException | RemoteException e) {
            String message = "Impossible de se connecter au serveur. Veuillez vérifier que :\n"
                    + "\t- Vous avez lancé le serveur de jeu avant de lancer le client.\n"
                    + "\t- Votre client est sur le même réseau que votre serveur.\n"
                    + "\t- ...";
            JOptionPane.showMessageDialog(this,message,"Erreur de connexion",JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonRemoteActionPerformed

    private void jButtonLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalActionPerformed

        JFrame frame = (JFrame) SwingUtilities.getRoot(this);

        generalPanel = new PanelGeneral();
        
        frame.setContentPane(generalPanel);

        repackPartieQuarto(generalPanel);
    }//GEN-LAST:event_jButtonLocalActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.drawImage(backgroundImage, 0, 0, this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLocal;
    private javax.swing.JButton jButtonRemote;
    // End of variables declaration//GEN-END:variables
}
