/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package launcher.remote;

import Network.RMI.Interface.ILogin;
import Network.RMI.Interface.ISession;
import java.awt.BorderLayout;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Anis
 */
public class ModeReseau extends JFrame {

    private final ILogin service;
    private final TestPane pane;

    private ISession session;

    private static ModeReseau instance;

    public static ModeReseau getInstance(ILogin service) {
        if (instance == null) {
            instance = new ModeReseau(service);
        }
        return instance;
    }

    /**
     * Creates new form MenuReseau
     *
     * @param service
     */
    private ModeReseau(ILogin service) {
        initComponents();
        this.service = service;

        pane = new TestPane();
        Connexion connexion = new Connexion(service);
        pane.addPage("connexion", connexion);
        pane.addPage("menu", new Menu(session));
        pane.toggleNavBar();
        this.getContentPane().add(pane, BorderLayout.CENTER);
    }

    public void setSession(ISession session) {
        if (this.session == null) {
            this.session = session;
            pane.setCurrentPage(1);
            pane.toggleNavBar();
            this.repaint();
        }
    }

    public void logout() {
        try {
            session.logout();
        } catch (RemoteException ex) {
            Logger.getLogger(ModeReseau.class.getName()).log(Level.SEVERE, null, ex);
        }
        session = null;
        pane.setCurrentPage(0);
        pane.toggleNavBar();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titre.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre.setText("MODE RESEAU");
        getContentPane().add(Titre, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titre;
    // End of variables declaration//GEN-END:variables
}
