/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package launcher.remote.view;

import Database.Compte;
import Network.RMI.Exceptions.PartieDoublonException;
import Network.RMI.Interface.ISession;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.rmi.RemoteException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.Parametre;
import view.GUIImageTool;

/**
 *
 * @author timotheetroncy
 */
public class JPanelParametresReseau extends javax.swing.JPanel {

    private final Image backgroundImage;
    private final ISession session;
    private Compte Adversaire;

    /**
     * Creates new form JPanelParametres
     */
    public JPanelParametresReseau(ISession session) {
        initComponents();
        this.backgroundImage = GUIImageTool.getImage("/images/wood_texture.jpg");
        this.session = session;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CommencerPartie = new javax.swing.JButton();
        RetourMenu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Taille = new javax.swing.JCheckBox();
        Creux = new javax.swing.JCheckBox();
        Couleur = new javax.swing.JCheckBox();
        Forme = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        QuartoCarre = new javax.swing.JCheckBox();
        QuartoAutoValidation = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        JoueurRandom = new javax.swing.JCheckBox();
        PseudoAdversaire = new javax.swing.JTextField();
        NomPrenomAdversaire = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        jPanel2.setMinimumSize(new java.awt.Dimension(100, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 70));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton3.setText("Rechercher");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jDialog1.getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jDialog1.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setName("parametres"); // NOI18N
        setOpaque(false);

        CommencerPartie.setText("Commencer la partie");
        CommencerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommencerPartieActionPerformed(evt);
            }
        });

        RetourMenu.setText("Retour au menu");
        RetourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourMenuActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Paramètres du jeu de pièce"));
        jPanel4.setOpaque(false);

        Taille.setSelected(true);
        Taille.setText("Taille");
        Taille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TailleActionPerformed(evt);
            }
        });

        Creux.setSelected(true);
        Creux.setText("Creux");
        Creux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreuxActionPerformed(evt);
            }
        });

        Couleur.setSelected(true);
        Couleur.setText("Couleur");
        Couleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CouleurActionPerformed(evt);
            }
        });

        Forme.setSelected(true);
        Forme.setText("Forme");
        Forme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Taille)
                    .addComponent(Forme)
                    .addComponent(Couleur)
                    .addComponent(Creux))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Taille)
                .addGap(18, 18, 18)
                .addComponent(Forme)
                .addGap(18, 18, 18)
                .addComponent(Couleur)
                .addGap(18, 18, 18)
                .addComponent(Creux)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Paramètrage du Quarto"));
        jPanel5.setOpaque(false);

        QuartoCarre.setSelected(true);
        QuartoCarre.setText("Activation Quarto par assemblage carré groupé");
        QuartoCarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuartoCarreActionPerformed(evt);
            }
        });

        QuartoAutoValidation.setText("Activation de la validation automatique du Quarto");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuartoAutoValidation)
                    .addComponent(QuartoCarre))
                .addGap(72, 72, 72))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(QuartoCarre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuartoAutoValidation)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adversaire"));
        jPanel1.setOpaque(false);

        JoueurRandom.setText("Désignation aléatoire du premier joueur");
        JoueurRandom.setEnabled(false);
        JoueurRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoueurRandomActionPerformed(evt);
            }
        });

        PseudoAdversaire.setEnabled(false);

        NomPrenomAdversaire.setEnabled(false);

        jLabel1.setText("Pseudo");

        jLabel2.setText("NOM - Prénom");

        jButton1.setText("Chercher Joueur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PseudoAdversaire)
                    .addComponent(NomPrenomAdversaire))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(JoueurRandom))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(PseudoAdversaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(NomPrenomAdversaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(JoueurRandom)
                .addGap(45, 45, 45))
        );

        jButtonReset.setText("Paramètres par défaut");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RetourMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReset)
                        .addGap(27, 27, 27)
                        .addComponent(CommencerPartie))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CommencerPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RetourMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TailleActionPerformed
        if (!this.Couleur.isSelected() && !this.Creux.isSelected() && !this.Forme.isSelected()) {
            this.Taille.setSelected(true);
        }
    }//GEN-LAST:event_TailleActionPerformed

    private void CouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CouleurActionPerformed
        if (!this.Taille.isSelected() && !this.Creux.isSelected() && !this.Forme.isSelected()) {
            this.Couleur.setSelected(true);
        }
    }//GEN-LAST:event_CouleurActionPerformed

    private void QuartoCarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuartoCarreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuartoCarreActionPerformed

    private void RetourMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourMenuActionPerformed
        CardLayout cl = (CardLayout) this.getParent().getLayout();
        cl.show(this.getParent(), "menu");
    }//GEN-LAST:event_RetourMenuActionPerformed

    private void CommencerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommencerPartieActionPerformed
        try {
            if (Adversaire == null) {

                ModeReseau2.getInstance().creerPartie(getParametres());

            } else {
                ModeReseau2.getInstance().creerPartieAvecAdversaire(getParametres(), Adversaire);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(JPanelParametresReseau.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PartieDoublonException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);

            Logger.getLogger(JPanelParametresReseau.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CommencerPartieActionPerformed

    private void FormeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormeActionPerformed
        if (!this.Couleur.isSelected() && !this.Creux.isSelected() && !this.Taille.isSelected()) {
            this.Forme.setSelected(true);
        }
    }//GEN-LAST:event_FormeActionPerformed

    private void CreuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreuxActionPerformed
        if (!this.Couleur.isSelected() && !this.Taille.isSelected() && !this.Forme.isSelected()) {
            this.Creux.setSelected(true);
        }
    }//GEN-LAST:event_CreuxActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        this.QuartoCarre.setSelected(true);
        this.JoueurRandom.setSelected(true);
        this.QuartoAutoValidation.setSelected(false);
        this.Taille.setSelected(true);
        this.Forme.setSelected(true);
        this.Creux.setSelected(true);
        this.Couleur.setSelected(true);

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void JoueurRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoueurRandomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JoueurRandomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            List<Compte> listeComptes = session.listeComptes();
            initList(listeComptes);
            this.jDialog1.setVisible(true);
            jDialog1.pack();
        } catch (RemoteException ex) {
            Logger.getLogger(JPanelParametresReseau.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Adversaire = null;
        PseudoAdversaire.setText("");
        NomPrenomAdversaire.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private Parametre getParametres() {
        return new Parametre(
                this.Forme.isSelected(),
                this.Taille.isSelected(),
                this.Couleur.isSelected(),
                this.Creux.isSelected(),
                this.QuartoCarre.isSelected(),
                this.QuartoAutoValidation.isSelected(),
                this.JoueurRandom.isSelected(),
                false,
                false,
                -1
        );
    }

    public JCheckBox getCouleur() {
        return Couleur;
    }

    public JCheckBox getCreux() {
        return Creux;
    }

    public JCheckBox getForme() {
        return Forme;
    }

    public JCheckBox getJoueurRandom() {
        return JoueurRandom;
    }

    public JCheckBox getQuartoAutoValidation() {
        return QuartoAutoValidation;
    }

    public JCheckBox getQuartoCarre() {
        return QuartoCarre;
    }

    public JCheckBox getTaille() {
        return Taille;
    }

    private int getAge(Date getBirthDate) {
        long ageInMillis = new Date().getTime() - getBirthDate.getTime();

        Date age = new Date(ageInMillis);

        return age.getYear();

    }

    private Date getRandomDate() {
        long offset = Timestamp.valueOf("2010-01-01 00:00:00").getTime();
        long end = Timestamp.valueOf("2015-01-01 00:00:00").getTime();
        long diff = end - offset + 1;
        Timestamp rand = new Timestamp(offset + (long) (Math.random() * diff));
        return new Date(rand.getTime());
    }

    public void initList(List<Compte> list) {
        Object data[][] = new Object[list.size()][6];
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        for (int i = 0; i < list.size(); i++) {
            data[i][0] = list.get(i).pseudo;
            data[i][1] = list.get(i).Nom;
            data[i][2] = list.get(i).Prenom;
            data[i][3] = getAge(list.get(i).naissance);
            data[i][4] = getRandomDate();
            data[i][5] = list.get(i);

        }
        this.jTable1.setModel(new Model(data));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int col = jTable1.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {

                    jDialog1.setVisible(false);
                    Adversaire = (Compte) jTable1.getModel().getValueAt(row, 5);
                    PseudoAdversaire.setText(jTable1.getValueAt(row, 0).toString());
                    NomPrenomAdversaire.setText(
                            jTable1.getModel().getValueAt(row, 1).toString().toUpperCase()
                            + " - "
                            + jTable1.getModel().getValueAt(row, 2).toString());

                }
            }
        });
    }

    class Model extends AbstractTableModel {

        private final String[] columnNames = {"PSEUDO", "NOM", "PRENOM", "AGE", "DATE D'INSCRIPTION"};
        private Object[][] data = null;

        public Model(Object[][] data) {
            this.data = data;
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public int getRowCount() {
            return data.length;
        }

        @Override
        public String getColumnName(int col) {

            return columnNames[col];
        }

        @Override
        public Object getValueAt(int row, int col) {
            return data[row][col];
        }

        @Override
        public Class getColumnClass(int col) {
            return getValueAt(0, col).getClass();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CommencerPartie;
    private javax.swing.JCheckBox Couleur;
    private javax.swing.JCheckBox Creux;
    private javax.swing.JCheckBox Forme;
    private javax.swing.JCheckBox JoueurRandom;
    private javax.swing.JTextField NomPrenomAdversaire;
    private javax.swing.JTextField PseudoAdversaire;
    private javax.swing.JCheckBox QuartoAutoValidation;
    private javax.swing.JCheckBox QuartoCarre;
    private javax.swing.JButton RetourMenu;
    private javax.swing.JCheckBox Taille;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.drawImage(backgroundImage, 0, 0, this);
    }
}
